### PR TITLE
Fix #138

### LINKED ISSUE #138: False positiv when directory in the conf directory
Linter produce an error error `[Errno 21] Is a directory` when checking configurations files if there is a directory inside it.
For example see [https://ci-apps.yunohost.org/ci/job/24027](https://ci-apps.yunohost.org/ci/job/24027)

### PR DESCRIPTION
**Pull request by ewilly**
## Problem

- cf #138 
- if a subfolder exist in conf directory the `bind_public_ip` test:
1. produce an error 
2. dont test file in it

## Solution

- lookup for file only including those in subfolder

## PR checklist

- [X] PR finished and ready to be reviewed

### CODE REVIEW

**Review by Tagadda — APPROVED** [review]
Looks good!

**Review by OniriCorpe — APPROVED** [review]
not enough used to python to see if anything is buggy, but seems good

**Comment by Psycojoker** [comment]
idk the functional part of this code but the python part looks very correct and not buggy

**Comment by OniriCorpe** [comment]
so LGTM

**Pull request merged**
