### PR TITLE
[mod] manifest: check 'version' field.

### PR DESCRIPTION
**Pull request by M5oul**
May not be merge since https://github.com/YunoHost/package_linter/issues/7 is not fixed.
We could add this check to 'to enhance'.

### CODE REVIEW

**Comment by alexAubin** [comment]
(Bump ?)

**Comment by M5oul** [comment]
Someone was not agree making this field mandatory. Maybe @Psycojoker?
It could be great to not make this field mandatory on the code.

**Comment by Psycojoker** [comment]
Not met (or I don't remember).

**Comment by maniackcrudelis** [comment]
This field is now required for some helpers.
And it's really usefull for packagers and users.

**Comment by zamentur** [comment]
I close it beacause version has been added by an other way. Thanks !

**Pull request closed without merging**
